#pragma once

#define FIFO_RUBY_CAMERA1 "/tmp/ruby/fifocam1"
#define FIFO_RUBY_AUDIO1 "/tmp/ruby/fifoaudio1"
#define FIFO_RUBY_AUDIO_QUEUE "/tmp/ruby/fifoaudioqueue"
#define FIFO_RUBY_AUDIO_BUFF "/tmp/ruby/fifoaudiobuff"

// Must be same name used by video player when it's using fifo pipes
#define FIFO_RUBY_STATION_VIDEO_STREAM_DISPLAY "/tmp/ruby/fifovideo_disp"
#define FIFO_RUBY_STATION_VIDEO_STREAM_RECORDING "/tmp/ruby/fifovideo_rec"
#define FIFO_RUBY_STATION_VIDEO_STREAM_ETH "/tmp/ruby/fifovideo_eth"

#define SEMAPHORE_RESTART_VIDEO_STREAMER "RUBY_SEM_RESTART_VIDEO_STREAMER"
#define SEMAPHORE_VIDEO_STREAMER_OVERLOAD "RUBY_SEM_VIDEO_STREAMER_OVERLOAD"

#define RUBY_SEM_RX_RADIO_HIGH_PRIORITY "RUBY_SEM_RX_RADIO_HIGH_PRIORITY"
#define RUBY_SEM_RX_RADIO_REG_PRIORITY "RUBY_SEM_RX_RADIO_REG_PRIORITY"

#define SEMAPHORE_SM_VIDEO_DATA_AVAILABLE "RUBY_SEM_SM_VIDEO_DATA_AVAILABLE"
#define SEMAPHORE_MPP_DISPLAY_FRAME_READY "RUBY_SEM_MPP_DISPLAY_FRAME_READY"
#define SEMAPHORE_MPP_DECODER_STALLED "RUBY_SEM_MPP_STALLED"
#define SEMAPHORE_MPP_DECODER_NO_NEW_OUTPUT "RUBY_SEM_MPP_NO_NEW_OUTPUT"

#define SEMAPHORE_RESTART_VEHICLE_PROCS "RUBY_SEM_RESTART_V_PROCS"
#define SEMAPHORE_STOP_VEHICLE_COMMANDS "RUBY_SEM_STOP_V_COMMANDS"
#define SEMAPHORE_STOP_VEHICLE_RC_RX "RUBY_SEM_STOP_V_RC_RX"
#define SEMAPHORE_STOP_VEHICLE_TELEM_TX "RUBY_SEM_STOP_V_TELEM_TX"
#define SEMAPHORE_STOP_VEHICLE_ROUTER "RUBY_SEM_STOP_V_ROUTER"

#define SEMAPHORE_SET_RADIO_TX_POWER "RUBY_SEM_SET_TX_POWER"
#define SEMAPHORE_SET_MAJESTIC_PARAMS_ASYNC "RUBY_SEM_SET_MAJ_ASYNC"

#define SEMAPHORE_WATCHDOG_CONTROLLER_PAUSE "RUBY_SEM_WD_CTRL_PAUSE"
#define SEMAPHORE_WATCHDOG_CONTROLLER_RESUME "RUBY_SEM_WD_CTRL_RESUME"
#define SEMAPHORE_WATCHDOG_CONTROLLER_RESTART "RUBY_SEM_WD_CTRL_RESTART"

#define SEMAPHORE_VIDEO_FILE_PLAYBACK_WILL_FINISH "RUBY_SEM_VIDEO_PLAY_WILL_FINISH"
#define SEMAPHORE_VIDEO_FILE_PLAYBACK_FINISHED "RUBY_SEM_VIDEO_PLAY_FINISHED"
